initial DB modeling
wafflestudio/22-5-team9-server pull request #2
Opened 2024-12-29 15:05 UTC by cloNoey

DB(instaclone) 테이블 구성
- users
- followers
- posts
- stories
- media

구체적인 종속성은 설정하지 않은 상태이고, 기본 필드만 작성했습니다.

2024-12-30 01:26 UTC, dida0423 requested changes
수고하셨습니다! 정리가 잘 되었네요. 😄 

ER Diagram의 코멘트랑 포스트가 아직 반영 안된 것 같은데 맞을까요?

반영 안된 부분이랑 슬랙에서 말씀하신대로 세세한 필드 attribute 설정하면 좋은 뼈대가 될 것 같네요!

2024-12-30 01:26 UTC, dida0423 commented on instaclone/app/post/models.py
> +    story_id: Mapped[int] = mapped_column(BigInteger)
```suggestion
    post_id: Mapped[int] = mapped_column(BigInteger)
```
혹시 의도적으로 story_id로 설정하신걸까요? Post attribute가 아직 반영 안된 것 같네요.

2024-12-30 01:26 UTC, dida0423 commented on instaclone/app/user/models.py
> +    # phone_number : 010XXXXXXXX
핸드폰 번호 다른 국가는 생각 안해도 괜찮겠죠..?

2024-12-30 01:31 UTC, b1lly13 commented on instaclone/app/user/models.py
> +    # phone_number : 010XXXXXXXX
다른 국가도 고려하면 좋을 것 같긴 하네요..

2024-12-30 01:33 UTC, cloNoey commented on instaclone/app/post/models.py
> +    story_id: Mapped[int] = mapped_column(BigInteger)
앗..! post 작성하다가 자리를 옮겨서,, comment 구성까지 누락되었네요..! 수정해서 올리겠습니다!

2024-12-30 01:37 UTC, cloNoey commented on instaclone/app/user/models.py
> +    # phone_number : 010XXXXXXXX
인스타 회원가입창에서 핸드폰 번호 스펙 알아보려고 이것저것 해봤는데, 011/070/015/1544/1666/.... 이런 고려사항들이 생각보다 너무 많아져서, 기본 세팅으로 010XXXXXXXX(11글자 숫자열)로 하고 추후에 수정하면 좋을 것 같다는 생각 하에, 일단 저렇게 작성했습니다. 다른 국가도 생각하면 너무너무 좋을 것 같아요👍

2024-12-30 06:04 UTC, cloNoey commented
![화면 캡처 2024-12-30 150304](https://github.com/user-attachments/assets/7ce8e884-e471-42fa-92a7-bdfa2d56014f)

ER Diagram 참고해서 간단하게 relationship만 다음과 같이 수정해보았습니다!
테스트해보진 않은 상태라,, 확인부탁드립니다!

2024-12-30 12:34 UTC, dida0423 reviewed
깔끔하게 해주신 것 같아요!!

그런데 자꾸 수정 요청해서 죄송합니다 ㅠㅠ
수정요청이라기보다 의견 제시한 것도 있어요! 의견 다른 부분에서는 반영 안 하셔도 돼요!!!

감사합니다🥹🥹🥹

2024-12-30 12:34 UTC, dida0423 commented on instaclone/app/post/models.py
인스타 보면 포스트에 얼마 전에 올라왔는지 표시되는데, 그 피쳐를 위해 작성 시간 필드도 만들어두면 어떨까요? 나중에 탐색 페이지에서 최신순으로 이미지 올리는 데에도 유용할  것 같아요.

2024-12-30 12:34 UTC, dida0423 commented on instaclone/app/story/models.py
>      expiration_date: Mapped[DATETIME] = mapped_column(DATETIME)
스토리도 포스트와 마찬가지로 작성 시간을 기록하고 expiration_date는 calculated field로 계산하면 어떨까요?

2024-12-30 12:34 UTC, dida0423 commented on instaclone/app/user/models.py
>      # introduce: Mapped[str] = mapped_column(String(100))
아직 필드 스펙이 논의가 안되어서 이 부분들은 주석처리하신 것 같은데 이번에 프로필 조회/수정에 소개글까지 구현해놓는게 좋을 것 같아요... 혹시 여기 살려주실 수 있을까요?🥹

2024-12-30 12:34 UTC, dida0423 commented on instaclone/app/medium/models.py
> +    # # file_type (image, video, gif, ...)
아하.. 저는 비디오 형식을 생각 못하고 있었네요..! 파일 이름과 path로 모든 파일을 올릴 수 있으면 `image_id`를 `file_id`로 수정하는 게 좋을 것 같아요!

2024-12-31 04:27 UTC, cloNoey commented on instaclone/app/post/models.py
좋은 의견 너무 감사드립니다!

2024-12-31 04:28 UTC, cloNoey commented on instaclone/app/user/models.py
>      # introduce: Mapped[str] = mapped_column(String(100))
네네! 3개 다 살려둘까요?

2024-12-31 05:24 UTC, dida0423 commented on instaclone/app/user/models.py
>      # introduce: Mapped[str] = mapped_column(String(100))
넵!! 감사합니다!

2025-01-01 12:41 UTC, merged